"""Fix review relationships

Revision ID: 05a06f31c54a
Revises: 19c266c7eb0f
Create Date: 2022-02-26 14:13:54.272967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a06f31c54a'
down_revision = '19c266c7eb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['owner_id'], ['id'])
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['id'])
    op.drop_column('reviews', 'owner_id')
    # ### end Alembic commands ###
