"""Fix broken user bookshelf relationship 3

Revision ID: 19c266c7eb0f
Revises: 3f1a5a804e54
Create Date: 2022-02-24 15:34:25.173426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c266c7eb0f'
down_revision = '3f1a5a804e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookshelves_owner_id_fkey', 'bookshelves', type_='foreignkey')
    op.create_foreign_key(None, 'bookshelves', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookshelves', type_='foreignkey')
    op.create_foreign_key('bookshelves_owner_id_fkey', 'bookshelves', 'bookshelves', ['owner_id'], ['id'])
    # ### end Alembic commands ###
