"""Fix broken user bookshelf relationship

Revision ID: 2973eff5780d
Revises: 920fbaa6c3f9
Create Date: 2022-02-24 15:29:00.006809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2973eff5780d'
down_revision = '920fbaa6c3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookshelves_owner_id_fkey', 'bookshelves', type_='foreignkey')
    op.drop_column('bookshelves', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookshelves', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bookshelves_owner_id_fkey', 'bookshelves', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
