"""Fix broken user bookshelf relationship 2

Revision ID: 3f1a5a804e54
Revises: 2973eff5780d
Create Date: 2022-02-24 15:31:02.336703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1a5a804e54'
down_revision = '2973eff5780d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookshelves', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookshelves', 'bookshelves', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookshelves', type_='foreignkey')
    op.drop_column('bookshelves', 'owner_id')
    # ### end Alembic commands ###
