"""Add user username

Revision ID: 68329c439f91
Revises: 3a9ed49d89ff
Create Date: 2022-03-14 16:55:56.475501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68329c439f91'
down_revision = '3a9ed49d89ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
