"""Add actual identifiers to the user table

Revision ID: c034ea99323e
Revises: 05a06f31c54a
Create Date: 2022-02-26 14:50:27.140047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c034ea99323e'
down_revision = '05a06f31c54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
